### ISSUE TITLE
Commentable在Attachment STI相關Model的sync new失敗

### ISSUE THREAD

**Issue by bdsword** [NCU-BRATS/Conflux#129]
原因大概是因為Attachment因為採用STI所以
https://github.com/NCU-BRATS/Conflux/blob/master/app/models/comment.rb#L17
這邊的commentable.class.name會找到Attachment::Post這種東西，可是comments在資料庫裡面卻是存Attachment所以找不到，把sync scope刪掉就會正常，可以間接驗證這點。

**Comment by jason1122g** [comment]
另外開一個scope之類的吧

**Comment by rueian** [comment]
當初不是把儲存sti全名關掉嗎，如果再開起來會不會有影響？
2015年1月30日 上午11:40 於 "JasonChiu" <notifications@github.com> 寫道：

**Comment by rueian** [comment]
#114 

在 sync_scope 去設定 type 範圍的時候要符合 STI 的 base_class
