### ISSUE TITLE
Attachment Counter Cache

### ISSUE THREAD

**Issue by rueian** [NCU-BRATS/Conflux#151]
在 project 上分類別儲存個別 Attachment 的 counter cache
並在 attachment index 的分類按鈕旁邊以 semantic-ui 的 label 顯示

關於如何更新 label 上的計數，可考慮用 sync 或是 js response

counter cache 的實作可以用 rails 內建的 counter_cache 或是 counter_culture

**Comment by jason1122g** [comment]
use counter_culture in #161
