### ISSUE TITLE
channel 調整

### ISSUE THREAD

**Issue by rueian** [NCU-BRATS/Conflux#155]
- [x] message input 變大後，不會變回去
- [ ] message 經過 sync 更新後，沒有根據條件重新套上 inline-message css class
- [x] message update form 會佔據整個 message container 的寬度，需與 avatar 對齊
- [x] channel 的新增刪除都需要創建 event
- [ ] 當 width < 768px 的時候 inline-message 會壞掉
- [x] channel 的輸入框會和新增訊息重疊，不利於使用
- [x] 在windows 上的 ie 和 chrome 會因為不明原因訊息擠在一起
- [x] channel 所屬的 sidebar，若名稱過長則會 wrap 至下一行，需要有更好的顯示方式
- [x] turbolink 會讓卷軸顯示壞掉
- [x] 刪除與編輯控制選項 在顯示時會擠高訊息

--------------------

- [x] 取消舊訊息的 sync，僅留 sync_new，model 的 ```sync :all``` 也改為只有新增時需要 sync
- [x] 舊訊息的更新由 js response 完成，不用 sync
- [x] 預設僅讀取前幾條訊息，往上滾再讀取更前面的訊息
- [ ] 訊息遇到日期切換時以 semantic-ui divider 隔開，並在 divider 上面標上日期
- [ ] 若卷軸位置不在最下面 更新其他資訊的時候 不應該自動下捲 且卷軸位置要正確

--------------------

- [ ] 刪除訊息後 畫面上的沒更新

**Comment by jason1122g** [comment]
7. channel 的輸入框會和新增訊息重疊，不利於使用
8. 在windows 上的 ie 和 chrome 會因為不明原因訊息擠在一起
9. channel 所屬的 sidebar，若名稱過長則會 wrap 至下一行，需要有更好的顯示方式

**Comment by jason1122g** [comment]
當 width < 768px 的時候 inline-message 會壞掉

這是 SEMANTIC UI 的問題

目前先不管

**Comment by rueian** [comment]
@jason1122g 第二項有問題，剛剛測試編輯訊息之後並沒有依據條件套上 inline-message css

不過請新的調整一起做：

- [] 取消舊訊息的 sync，僅留 sync_new
- [] 舊訊息的更新由 js response 完成
- [] 預設讀取當天的訊息，往上滾在讀取前一天的訊息。中間以 semantic-ui divider 隔開，並在 divider 上面標上日期

**Comment by jason1122g** [comment]
求測試情境

**Comment by rueian** [comment]
我隨便找一個前幾天的 inline-message 來編輯

編輯完之後沒有重新套上 inline-message

不過這個問題在取消 sync 之後應該很好修改
