### ISSUE TITLE
尋找 counter cache 用在 polymorphic 的解決方案

### ISSUE THREAD

**Issue by jason1122g** [NCU-BRATS/Conflux#168]
主要用於 comments 的計數

**Comment by rueian** [comment]
可能得自己做了，應該不難

或許可以綁進 Issue AASM 裡面

**Comment by rueian** [comment]
比較快的做法是在 Sprint 的 before_save 裡面直接去統計 Issue 數量

而 Issue 在需要的時候去 touch 他的 Sprint

**Comment by rueian** [comment]
這個功能自己做
