### ISSUE TITLE
研究 HTML::Pipeline::Filter 與製作 HTML Filter

### ISSUE THREAD

**Issue by rueian** [NCU-BRATS/Conflux#18]
Github 使用 https://github.com/jch/html-pipeline 這個 gem 來處理使用者輸入
裡面已經有內建許多 Filter ，例如 MentionFilter

目前 master 中已經安裝了 html-pipeline gem，而且在 app/html_pipeline_filters 也有一個我們自己的 RougeSyntaxHighlightFilter，是用 Rouge 來做 SyntaxHighlight 的 Filter

使用範例在 welcome#index

請幫忙研究這個東西以及它內建的 Filter 如何使用，並依我們自己的需求製作或修改 Filter

**Comment by jason1122g** [comment]
內建的 mention filter 看起來是沒辦法判斷使用者是否存在

如果要有這個功能 必須自己想辦法擴充他的

其他內建 filter 較單純 直接看文件就好
