### ISSUE TITLE
在已經參加的討論串中，被 Mention 時會收到重複的通知

### ISSUE THREAD

**Issue by rueian** [NCU-BRATS/Conflux#231]
![2015-04-30 01 19 51](https://cloud.githubusercontent.com/assets/2727535/7396869/22d09c8c-eed7-11e4-8e67-1e94569311a3.png)

如圖，如果在一個已經參加的討論串中被別人 Mention 了，就會收到兩個通知

應該做成不要收到第二個通知，也就是撰寫回覆的通知

**Comment by rueian** [comment]
可與 #239 一起做

都應該會需要用到檢查 mention 過的使用者來確認需不需要發通知

**Comment by rueian** [comment]
注意需將 Mention Notice 改成使用 Wisper 發送

**Comment by bdsword** [comment]
@213ffqewfeqfqw
