### ISSUE TITLE
製作 JS Responder 

### ISSUE THREAD

**Issue by rueian** [NCU-BRATS/Conflux#45]
**請參考 Flush Responder 製作 JS Responder 提供預設的 JS Response**

### 情景如下：
當我們透過 javascript 發送 request 的時候，rails server 收到的 request format 是 js，因此 rails 會去尋找 .js 的 view 來回覆，我們希望在沒有對應的 .js view 時，可以有一個預設的 javascript response 作為回覆。

例如 如果我們在一般的表單上面加上 date-remote="true" ，那麼在提交表單的時候 jquery-ujs 將會攔截預設的瀏覽器表單提交行為，然後會透過 ajax 幫我們提交。當 server 收到後，我們希望可以回傳一個預設的 javascript response 給瀏覽器，而不用針對 controller#action 去寫一個 .js 的 view

### 需求如下：
當**沒有存在對應的 js view 時**，回傳預設的 JS Response:

  1. 若 post/put/patch/delete 成功，回傳 javascript 在頁面中創建成功 notice，3秒後 notice 會自動消失
  2. 若 post/put/patch/delete 失敗，回傳 javascript 在頁面中創建失敗 alert ，並附上 error message，附上關閉按鈕可將 alert 關閉
  3. 其他 get 等 request 可不處理

notice 與 alert 可參考 app/views/layouts/_notice.html.slim

**Comment by jason1122g** [comment]
> 當沒有存在對應的 js view 時，回傳預設的 JS Response

有沒有可能就算有對應的js view存在 還是想要用那些你說的創建成功/失敗 notice ?

**Comment by rueian** [comment]
這樣感覺有點困難，如果是這樣的話需要合併 Responder 的 response 跟 view

不知道可不可以做得到

**Comment by rueian** [comment]
#49 完成
