### ISSUE TITLE
專案成員 可以新增修改刪除瀏覽 Issue

### ISSUE THREAD

**Issue by rueian** [NCU-BRATS/Conflux#6]
專案成員 可以在該專案下創建issue

Issue 本身只帶 title 不帶內容
用第一個 comment 作為其內容，如 github 的 issue 系統

Issue 使用 sequenced gem 來產生 serial id
https://github.com/djreimer/sequenced

sequenced scope 需設定為 peoject id

Issue 的 status 分為
Open
Closed
使用 aasm gem 管理 Issue 狀態
https://github.com/aasm/aasm
並將原本的 status 欄位改名成 aasm 的預設 aasm_state 

Issue 可以指定多個 assignees
Issue 可以指定所屬 Sprint

**Comment by jason1122g** [comment]
done since a6cc2ad53852a4d20699adf0a4a6717c91cbb8b3
